### ISSUE TITLE
Dogfood hindent

### ISSUE THREAD

**Issue by phadej** [mihaimaruseac/hindent#432]
Should hindent use hindent?

**Comment by NorfairKing** [comment]
Make it a pre-commit hook, so no-one can commit any changes that break the formatting of hindent itself.
Make sure to document a lot of hindent as well, so you can make sure that comments don't break anything, etc...

**Comment by justanotherdot** [comment]
I tried out hindent today and was confused by the results I got compared to hindent's codebase, so I felt I should chime in and say +1 to this. 

Are imports no longer formatted similarly to what is currently on top of master?

I'd be happy to try to find the time to help out if PRs are welcome for this.

**Comment by justanotherdot** [comment]
I've made an initial PR that attempts to run `hindent` on `src/*.hs`. The PR, as of writing this, does not include any automated process @NorfairKing mentioned, but I'm happy to oblige if I'm wrong in that it's repo-to-repo or if there's an alternative, automated solution that might help. It also currently fails on `Pretty.hs` because of bug #383, but if I find time I'll try to see if I can take a crack at fixing that, as well.

**Comment by justanotherdot** [comment]
**update** I've closed the PR and will instead try to address the problems I encountered if I can find time.

**Comment by toku-sa-n** [comment]
Closing as CI checks the format of HIndent's source code with HIndent.
