### ISSUE TITLE
Why put case on a new line?

### ISSUE THREAD

**Issue by mat8913** [mihaimaruseac/hindent#448]
According to Johan "the default and only style" Tibell:

> The alternatives in a case expression can be indented using either of
> the two following styles:
> 
> ```haskell
> foobar = case something of
>     Just j  -> foo
>     Nothing -> bar
> ```
> 
> or as
> 
> ```haskell
> foobar = case something of
>              Just j  -> foo
>              Nothing -> bar
> ```

But, hindent changes it to

```haskell
foobar =
    case something of
        Just j -> foo
        Nothing -> bar
```

**Comment by sighingnow** [comment]
I'm in favor of current style for the more compact layout.

>
> ~~~
> foobar = case something of
>     Just j  -> foo
>     Nothing -> bar
> ~~~

If the first line is very long then the `case` statement and the condition expression will be placed far from the cases in the following lines.

>
> ~~~
> foobar = case something of
>              Just j  -> foo
>              Nothing -> bar
> ~~~

Also for the same reason, if the first long is very long, we width of the code block following `case` will be limited due to the global line length limit.

**Comment by toku-sa-n** [comment]
Closing as the current style seems to be reasonable.
