### ISSUE TITLE
Formatting of newtype

### ISSUE THREAD

**Issue by normenmueller** [mihaimaruseac/hindent#546]
## Question

Has the formatting of `newtype` changed? (`hindent 5.3.0`) 

```
newtype App = App
    { aString :: String
    }
```

is now formatted as follows

```
newtype App =
    App
        { aString :: String
        }
```

No longer conform to [Data Declarations](https://github.com/tibbe/haskell-style-guide/blob/master/haskell-style.md#data-declarations).

**Comment by toku-sa-n** [comment]
@mihaimaruseac What do you think about this? I feel both the current and previous implementations are weird because they add a new line after the constructor name, but I think keeping it on the same line as the start of the record is good.

Thus, I have these styles in my mind. They also apply to usual data declarations.

```haskell
data App = App { aString :: String
               }
```

```haskell
data App
  = App { aString :: String
        }
  | AnyOtherConstructors
```

Of course, not changing anything is undoubtedly an option, though.

**Comment by mihaimaruseac** [comment]
In general I prefer

```hs
data App = App
    { aString :: String
    } deriving ...
```

As it minimizes diffs if a name changes, if a field is added/removed/reordered. Not using record syntax with other constructors though.

**Comment by mihaimaruseac** [comment]
Happy new year!

I never used data defs with multiple constructors and record syntax as it creates partial functions. But in cases where these get used, I think the last listing is more readable, although you are in right in the fact that it breaks consistency.

I'm ok either with the last sample or with the second one. The first one makes it easy to miss that there is a secondary constructor.
